DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS location;

CREATE TABLE author (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  author_name VARCHAR(30) NOT NULL
);

CREATE TABLE location (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  isle INTEGER NOT NULL,
  row_letter VARCHAR(5) NOT NULL
);

CREATE TABLE books(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR (50) NOT NULL,
  code INTEGER (10) NOT NULL,
  author_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE CASCADE,
  CONSTRAINT fk_location FOREIGN KEY (location_id) REFERENCES location(id) ON DELETE CASCADE
);